### ISSUE TITLE
Make the links open in a new tab/window

### ISSUE THREAD

**Issue by fcculsan** [fcculsan/fcculsan_ontheweb#15]
Currently, the links on our website open in the same window. Please change them so they open in a new tab/window.

You will need to change an attribute of each `<a>` element.

If you have any questions or need a help, you can ask here.

**Comment by vlastikwalker** [comment]
@fcculsan Mind if I handle this issue? Still getting familiar with contributing to opensource projects.

**Comment by fcculsan** [comment]
Thanks @vlastikczech! Your contribution is really appreciated. Looks like you're off to a good start with open source already!

Just wondering, how did you find our issue? I can't believe how quick you were!
